---
title: "ICCS datafiles 1999/2009/2016/2022"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
editor_options: 
  chunk_output_type: console
---

# Files available

Selected countries and years (cycle) to analyse 

```{r setup, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = 'C:/Users/pamel/OneDrive - KU Leuven/Master in Statistics/Master Thesis')
library(haven)
library(readxl)
library(tidyverse)


setwd("C:/Users/pamel/OneDrive - KU Leuven/Master in Statistics/Master Thesis/")

Countries <- read_xlsx("Data_analysis/Metadata.xlsx", sheet = "CNT")
Files <- read_xlsx("Data_analysis/Metadata.xlsx", sheet = "Files")


CNT = c("ITA","CHL") #,"BFL","PER"

years <- Countries %>% filter(AlphaCode %in% CNT & !is.na(Part)) %>% dplyr::select(Country, AlphaCode, year) 

```

```{r namesfiles, comment=""}
filenames <- NULL
print("Countries selected and year participation in ICCS:")

for (cnt in CNT) {

  yearf <- years %>% filter(AlphaCode == cnt & year != 22) %>% arrange(as.numeric(year))
  
  print(paste0(unique(yearf$Country), " :", paste(sort(ifelse(yearf$year == "99", paste0("19",yearf$year), paste0("20",yearf$year))), collapse = " ")))

  for (year in yearf$year) {
 
    if (year == "99") Folder <- paste0("CivED19",year,"_IDB_SPSS_G8") else
      Folder <- paste0("ICCS20",year,"_IDB_SPSS")
    CountryEU <- Countries %>% filter(year == year & !is.na(EUQ)) %>% dplyr::select(AlphaCode)
    CountryLA <- Countries %>% filter(year == year & !is.na(LAQ)) %>% dplyr::select(AlphaCode) 
    File <- Files %>% filter(!is.na(ToUse)) %>% dplyr::select(Filename)
    if (year == "99") cycle = "f2" else if (year == "09") cycle = "C2" else if (year == "16") cycle = "C3" else 
      if (year == "22") cycle = "C4"
    if (year == "99") {
      filenames <- c(filenames, paste0(Folder, "/Data/", "bs_", tolower(cnt), cycle,".sav"))
      filenames <- c(filenames, paste0(Folder, "/Data/", "bt_", tolower(cnt), cycle,".sav"))
      filenames <- c(filenames, paste0(Folder, "/Data/", "bc_", tolower(cnt), cycle,".sav"))
    } else {
      if (cnt %in% CountryLA$AlphaCode) filenames <- c(filenames, paste0(Folder, "/Data/", "ISL",cnt,cycle,".sav"))
      if (cnt %in% CountryEU$AlphaCode) filenames <- c(filenames, paste0(Folder, "/Data/", "ISE",cnt,cycle,".sav")) 
      filenames <- c(filenames, paste0(Folder, "/Data/", "ISG",cnt,cycle,".sav"))
      filenames <- c(filenames, paste0(Folder, "/Data/", "ITG",cnt,cycle,".sav"))
      filenames <- c(filenames, paste0(Folder, "/Data/", "ICG",cnt,cycle,".sav")) 
    }
  }
}
#order by questionnaire and cycle
filenames <- filenames[order(substr(filenames,24,26),substr(filenames,30,31))] 
rm(list = c("yearf", "cnt", "cycle", "Folder", "year", "File", "CountryEU", "CountryLA"))
```

```{r read_spss, eval=FALSE}
ICGC1 <- NULL
ICGC2 <- NULL
ICGC3 <- NULL
ITGC1 <- NULL
ITGC2 <- NULL
ITGC3 <- NULL
ISGC1 <- NULL
ISGC2 <- NULL
ISGC3 <- NULL
ISEC2 <- NULL
ISEC3 <- NULL
ISLC2 <- NULL
ISLC3 <- NULL

for (nc in 1:length(filenames)) {
  
  if (substr(filenames[nc],24,26) == "ICG" | substr(filenames[nc],28,30) == "bc_") {
    if (substr(filenames[nc],34,35) == "f2") {
      dataset <- read_sav(file.path("Magda files/Data", filenames[nc]))
      ICGC1 <- rbind(ICGC1, dataset)
    } else if (substr(filenames[nc],30,31) == "C2") {
      dataset <- read_sav(file.path("Magda files/Data", filenames[nc]))
      ICGC2 <- rbind(ICGC2, dataset)
    } else if (substr(filenames[nc],30,31) == "C3") {
      dataset <- read_sav(file.path("Magda files/Data", filenames[nc]))  
      ICGC3 <- rbind(ICGC3, dataset)
    }
  }
  if (substr(filenames[nc],24,26) == "ITG" | substr(filenames[nc],28,30) == "bt_"){
    if (substr(filenames[nc],34,35) == "f2") {
      dataset <- read_sav(file.path("Magda files/Data", filenames[nc]))
      ITGC1 <- rbind(ITGC1, dataset)
    } else if (substr(filenames[nc],30,31) == "C2") {
      dataset <- read_sav(file.path("Magda files/Data", filenames[nc]))
      ITGC2 <- rbind(ITGC2, dataset)
    } else if (substr(filenames[nc],30,31) == "C3") {
      dataset <- read_sav(file.path("Magda files/Data", filenames[nc]))  
      ITGC3 <- rbind(ITGC3, dataset)
    }
  }
  if (substr(filenames[nc],24,26) == "ISG" | substr(filenames[nc],28,30) == "bs_"){
   if (substr(filenames[nc],34,35) == "f2") {
      dataset <- read_sav(file.path("Magda files/Data", filenames[nc]))
      dataset_r <- dataset %>% rename_at(vars(colnames(dataset)), ~ toupper(colnames(dataset)))
      ISGC1 <- rbind(ISGC1, dataset_r)
    } else if (substr(filenames[nc],30,31) == "C2") {
      dataset <- read_sav(file.path("Magda files/Data", filenames[nc]))
      ISGC2 <- rbind(ISGC2, dataset)
    } else if (substr(filenames[nc],30,31) == "C3") {
      dataset <- read_sav(file.path("Magda files/Data", filenames[nc]))  
      ISGC3 <- rbind(ISGC3, dataset)
    }
  }
  
  if (substr(filenames[nc],24,26) == "ISE") {
    if (substr(filenames[nc],30,31) == "C2") {
      dataset <- read_sav(file.path("Magda files/Data", filenames[nc]))
      ISEC2 <- rbind(ISEC2, dataset)
    } else if (substr(filenames[nc],30,31) == "C3") {
      dataset <- read_sav(file.path("Magda files/Data", filenames[nc]))  
      ISEC3 <- rbind(ISEC3, dataset)
    }
  }
  if (substr(filenames[nc],24,26) == "ISL") {
    if (substr(filenames[nc],30,31) == "C2") {
      dataset <- read_sav(file.path("Magda files/Data", filenames[nc]))
      ISLC2 <- rbind(ISLC2, dataset)
    } else if (substr(filenames[nc],30,31) == "C3") {
      dataset <- read_sav(file.path("Magda files/Data", filenames[nc]))  
      ISLC3 <- rbind(ISLC3, dataset)
    }
  }
}
ISGC1$cycle <- "C1"
ISGC2$cycle <- "C2"
ISGC3$cycle <- "C3"
ITGC1$cycle <- "C1"
ITGC2$cycle <- "C2"
ITGC3$cycle <- "C3"
ICGC1$cycle <- "C1"
ICGC2$cycle <- "C2"
ICGC3$cycle <- "C3"
ISEC2$cycle <- "C2"
ISEC3$cycle <- "C3"
ISLC2$cycle <- "C2"
ISLC3$cycle <- "C3"
rm(list = c("dataset","nc","filenames"))
```

```{r codebooks, eval=FALSE}

#Joining Questionnaires for Students 
tabISG3 <- read_xlsx("Data_analysis/ICCS2016MS_Codebook.xlsx", sheet = "ISGC3")
tabISG3 <- tabISG3 %>% dplyr::select(ID,VariableC3, VariableC2, VariableC1, Domain, Construct, Label, `Value Scheme Detailed`) %>% mutate(Dataset = "ISG")
tabISE3 <- read_xlsx("Data_analysis/ICCS2016MS_Codebook.xlsx", sheet = "ISEC3")
tabISE3 <- tabISE3 %>% dplyr::select(ID,VariableC3, VariableC2, VariableC1, Domain, Construct, Label, `Value Scheme Detailed`) %>% mutate(Dataset = "ISE")
tabISL3 <- read_xlsx("Data_analysis/ICCS2016MS_Codebook.xlsx", sheet = "ISLC3")
tabISL3 <- tabISL3 %>% dplyr::select(ID,VariableC3, VariableC2, VariableC1, Domain, Construct, Label, `Value Scheme Detailed`) %>% mutate(Dataset = "ISL")
tabITG3 <- read_xlsx("Data_analysis/ICCS2016MS_Codebook.xlsx", sheet = "ITGC3")
tabITG3 <- tabITG3 %>% dplyr::select(ID,VariableC3, VariableC2, VariableC1, Domain, Construct, Label, `Value Scheme Detailed`) %>% mutate(Dataset = "ITG")
tabICG3 <- read_xlsx("Data_analysis/ICCS2016MS_Codebook.xlsx", sheet = "ICGC3")
tabICG3 <- tabICG3 %>% dplyr::select(ID,VariableC3, VariableC2, VariableC1, Domain, Construct, Label, `Value Scheme Detailed`) %>% mutate(Dataset = "ICG")

VarsToUse <- tabISG3 %>% rbind(tabISE3) %>% rbind(tabISL3) %>% rbind(tabITG3) %>% rbind(tabICG3)
#save(VarsToUse, file = "Data_analysis/Codebook.RData")
VarsToUse <- VarsToUse %>% filter(!is.na(Construct))
rm("tabISG3", "tabISE3", "tabISL3", "tabITG3", "tabICG3")


idS <- VarsToUse %>% filter(Dataset == "ISG" & Construct == "ID Variables" & !VariableC3 %in% c("IDGRADE", "IDPOP", "IDBOOK")) %>% dplyr::select(VariableC3) %>%  pull()
idT <- VarsToUse %>% filter(Dataset == "ITG" & Construct == "ID Variables" & !VariableC3 %in% c("IDGRADE")) %>% dplyr::select(VariableC3) %>%  pull()
idC <- VarsToUse %>% filter(Dataset == "ICG" & Construct == "ID Variables" & !VariableC3 %in% c("IDGRADE")) %>% dplyr::select(VariableC3) %>%  pull()

```

```{r mergedata, eval=FALSE}
repet <- c("SAGE", "SGENDER", "TOTWGTS", "S_GENDER", "S_AGE")
 
#Merging student questionnaires same cycle, General + European + Latin American
varsC1 <- VarsToUse %>% filter(!is.na(VariableC1) & Dataset %in% c("ISG", "ISE", "ISL")) %>% dplyr::select(VariableC1) %>% pull()
varsC2 <- VarsToUse %>% filter(!is.na(VariableC2) & Dataset %in% c("ISG", "ISE", "ISL")) %>% dplyr::select(VariableC2) %>% pull()
varsC3 <- VarsToUse %>% filter(!is.na(VariableC3) & Dataset %in% c("ISG", "ISE", "ISL")) %>% dplyr::select(VariableC3) %>% pull()

ISC1 <- ISGC1[, colnames(ISGC1) %in% varsC1]

ISC2 <- ISGC2[, colnames(ISGC2) %in% c(varsC2, "cycle")] %>% 
  full_join(ISEC2[, colnames(ISEC2) %in% c(varsC2[!varsC2 %in% repet], "cycle")], by = c("cycle", idS)) %>% 
  full_join(ISLC2[, colnames(ISLC2) %in% c(varsC2[!varsC2 %in% repet], "cycle")], by = c("cycle", idS)) 

ISC3 <- ISGC3[, colnames(ISGC3) %in% c(varsC3, "cycle")] %>% 
  full_join(ISEC3[, colnames(ISEC3) %in% c(varsC3[!varsC3 %in% repet], "cycle")], by = c("cycle", idS)) %>% 
  full_join(ISLC3[, colnames(ISLC3) %in% c(varsC3[!varsC3 %in% repet], "cycle")], by = c("cycle", idS)) 

#rm(list = c("ISGC1","ISGC2","ISEC2","ISLC2","ISGC3","ISEC3","ISLC3"))

#Rename function, variables without IS2-IS3
rename_cycle <- function(dataset){
  names2 <- colnames(dataset)
  
  for (idv in 1:length(names2)) {
    if (substr(names2[idv],1,3) %in% c("IS2","IS3","ES2","ES3","LS2","LS3","IT2","IT3","IC2","IC3")) {
      names2[idv] <-  paste0(substr(names2[idv],1,2),substr(names2[idv],4,nchar(names2[idv])))
    }
    if (substr(names2[idv],1,2) %in% c()) {
      names2[idv] <-  paste0(substr(names2[idv],1,2),substr(names2[idv],4,nchar(names2[idv])))
    }
  }
  dataset_r <- dataset %>% rename_at(vars(colnames(dataset)), ~ names2)
}

#######Student files
# ISC2_r <- rename_cycle(ISC2)
# ISC3_r <- rename_cycle(ISC3)

#Setting (row bind) cycles for Students Questionnaires
ISC <- ISC1 %>%
  bind_rows(ISC2) %>%
  bind_rows(ISC3) #%>% 
  #nest(ISG = -c(cycle, COUNTRY, IDCNTRY, IDPOP))
#rm(list = c("ISC1","ISC2", "ISC3","ISC2_r", "ISC3_r"))


#######Teacher file
#Setting (row bind) cycles for Teacher Questionnaires
# ITGC2_r <- rename_cycle(ITGC2)
# ITGC3_r <- rename_cycle(ITGC3)

varsC1 <- VarsToUse %>% filter(!is.na(VariableC1) & Dataset == "ITG") %>% dplyr::select(VariableC1) %>% pull()
varsC2 <- VarsToUse %>% filter(!is.na(VariableC2) & Dataset == "ITG") %>% dplyr::select(VariableC2) %>% pull()
varsC3 <- VarsToUse %>% filter(!is.na(VariableC3) & Dataset == "ITG") %>% dplyr::select(VariableC3) %>% pull()

ITG <- ITGC1[, colnames(ITGC1) %in% c(varsC1, "cycle")] %>%
  bind_rows(ITGC2[, colnames(ITGC2) %in% c(varsC2, "cycle")]) %>%
  bind_rows(ITGC3[, colnames(ITGC3) %in% c(varsC3, "cycle")]) #%>% 
  #nest(ITG = -c(cycle, COUNTRY, IDCNTRY, IDPOP))
#rm(list = c("ITGC1","ITGC2", "ITGC3","ITGC2_r", "ITGC3_r"))

########School file
#Merging cycles for School Questionnaires
# ICGC2_r <- rename_cycle(ICGC2)
# ICGC3_r <- rename_cycle(ICGC3)

varsC1 <- VarsToUse %>% filter(!is.na(VariableC1) & Dataset == "ICG") %>% dplyr::select(VariableC1) %>% pull()
varsC2 <- VarsToUse %>% filter(!is.na(VariableC2) & Dataset == "ICG") %>% dplyr::select(VariableC2) %>% pull()
varsC3 <- VarsToUse %>% filter(!is.na(VariableC3) & Dataset == "ICG") %>% dplyr::select(VariableC3) %>% pull()

ICG <- ICGC1[, colnames(ICGC1) %in% c(varsC1, "cycle")] %>%
  bind_rows(ICGC2[, colnames(ICGC2) %in% c(varsC2, "cycle")]) %>%
  bind_rows(ICGC3[, colnames(ICGC3) %in% c(varsC3, "cycle")]) #%>% 
  #nest(ICG = -c(cycle, COUNTRY, IDCNTRY, IDPOP))
#rm(list = c("ICGC1","ICGC2", "ICGC3","ICGC2_r", "ICGC3_r"))

ICCS <- ISC %>% full_join(ITG, by = c("cycle", idC)) %>% full_join(ICG, by = c("cycle", idC))
save(ICCS, file = "Data_analysis/ICCS.RData")

#rm(list = c("idT", "idC", "idS"))
```

# Description of variables  

```{r descriptive, fig.height= 3, results = 'asis'}
load("Data_analysis/ICCS.RData")
load("Data_analysis/Codebook.RData")

constr <- c("Attitudes toward equal rights for immigrants",
            "Attitudes toward gender equality",
            "Attitudes toward equal rights for all ethnic/racial groups")

sys.source("Data_analysis/Descriptive_Analysis.R", envir = knitr::knit_global())

```

# Confirmatory Factor Analysis (CFA)  

```{r cfa}

sys.source("Data_analysis/cfa.R", envir = knitr::knit_global())

```

# Latent Class Analysis  (LCA)

```{r}
library(poLCA)
#LCA1 <- poLCA(, data = ICCS, nclass = 2, graphs = TRUE, na.rm = TRUE)
```

